version: '1.0'
services:
  postgres:
    image: pgvector/pgvector:0.8.0-pg17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=vector_store
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    logging:
      options:
        max-size: 10m
        max-file: "3"  
    ports:
      - '5432:5432'